name: PR

on:
  pull_request:
    branches: [ master ]


jobs:
  gomod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [
          '1.18',
          '1.17',
          '1.16',
          '1.15',
          '1.14',
        ]
        branch: [ '.', './v3' ]
    name: Go ${{ matrix.go }}.x PR Validate ${{ matrix.branch }} (Modules)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Version
        run: go version
      - name: Build and Validate
        run: |
          cd ${{ matrix.branch }}
          go vet .
          go test .
          go test -cover -race -cpu 1,2,4 .
          go build .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
          only-new-issues: true

